name = "portfolio-api"
main = "src/index.ts"
compatibility_date = "2024-12-20"

# 開発環境設定
[env.development]
vars = { ENVIRONMENT = "development" }

# 本番環境設定
[env.production]
vars = { ENVIRONMENT = "production" }

# D1データベース設定
# 実際のデプロイ時にbinding設定を追加
[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "YOUR_DATABASE_ID" # wrangler d1 create実行後に置き換え

# R2ストレージ設定
# 実際のデプロイ時にbinding設定を追加
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "portfolio-assets"

# KVネームスペース設定（キャッシュ用）
# 実際のデプロイ時にbinding設定を追加
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_ID" # wrangler kv:namespace create実行後に置き換え